# -*- coding: utf-8 -*-
"""教育大數據作業.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rZ-uFzuGdvCk7X3Vw39lqQWcoVjdMxPB
"""

# 1-1
import pandas as pd

df = pd.read_csv('/edu_bigdata_imp1.csv', encoding='big5', low_memory=False)

df_filtered= df[df['PseudoID']==39]

unique_values = df_filtered['dp001_review_sn'].unique()

print(len(unique_values))

# 1-2
import pandas as pd
df = pd.read_csv('/edu_bigdata_imp1.csv',encoding='big5',low_memory=False)
df_filtered = df[df['PseudoID']==39]
df_filtered = df_filtered.dropna(subset=['dp001_question_sn'])
unique_values = df_filtered['dp001_question_sn'].unique()

print(len(unique_values))

# 2-1
import pandas as pd
df = pd.read_csv('/edu_bigdata_imp1.csv',encoding='big5',low_memory=False)
df_filtered = df[df['PseudoID']==281]
df_filtered = df_filtered.dropna(subset=['dp001_indicator'])
unique_values = df_filtered[['dp001_video_item_sn','dp001_indicator']].drop_duplicates()
unique_values['dp001_video_item_sn'] = unique_values['dp001_video_item_sn'].astype(int)

print(unique_values.values)

# 2-2
import pandas as pd
df = pd.read_csv('/edu_bigdata_imp1.csv',encoding='big5',low_memory=False)
df_filtered = df[df['PseudoID']==281]
df_filtered = df_filtered.dropna(subset=['dp001_prac_score_rate'])
df_score_rate_100 = df_filtered[df_filtered['dp001_prac_score_rate']==100]

print(len(df_score_rate_100))

# 3-1
import pandas as pd
df = pd.read_csv('/edu_bigdata_imp1.csv',encoding='big5',low_memory=False)
df_filtered = df[df['PseudoID']==71]
df_filtered = df_filtered.dropna(subset=['dp001_record_plus_view_action'])
df_paused = df_filtered[df_filtered['dp001_record_plus_view_action']=="paused"]

print(len(df_paused))

# 3-2
import pandas as pd
df = pd.read_csv('/edu_bigdata_imp1.csv',encoding='big5',low_memory=False)
df_filtered = df[df['PseudoID']==71]
df_date = pd.to_datetime(df_filtered['dp001_review_start_time']).dt.date
unique_values = df_date.unique()

print(unique_values)

# 4-1
import pandas as pd
df = pd.read_csv('/edu_bigdata_imp1.csv',encoding='big5',low_memory=False)
df_filtered = df['dp001_review_sn']
counter = df_filtered.value_counts()

print(counter.idxmax().astype(int),counter.max())

# 4-2
import pandas as pd
df = pd.read_csv('/edu_bigdata_imp1.csv',encoding='big5',low_memory=False)
df_filtered = df[df['dp002_extensions_alignment']=="[\"十二年國民基本教育類\"]"]

print(len(df_filtered))

# 4-3
import pandas as pd
df = pd.read_csv('/edu_bigdata_imp1.csv',encoding='big5',low_memory=False)
df_filtered = df['dp002_verb_display_zh_TW']
counter = df_filtered.value_counts()

print(counter.head(3).index)

# 4-4
import pandas as pd
df = pd.read_csv('/edu_bigdata_imp1.csv',encoding='big5',low_memory=False)
df_filtered = df[df['dp002_extensions_alignment']=="[\"校園職業安全\"]"]

print(len(df_filtered))